# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#
default: &default
	adapter: postgresql
	enconding: unicode

development:
	<<: *default
	database: mp01_devp
test:
	<<: *default
	database: mp01_test

production:
	<<: *default
	database: mp01_prod
